#!/bin/bash
#
# Installation script for the dotfiles, and to configure the Linux environment.
#
# Run using:
# $ ./install
#
# Author: Danylo Malyuta, 2020.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# ..:: Copy dotfiles to home directory ::..

# Bash
ln -sf "$DIR"/.profile ~
ln -sf "$DIR"/.bash_aliases ~
ln -sf "$DIR"/.local.bashrc ~
ln -sf "$DIR"/.bash_profile ~

# Various executable scripts
ln -sf "$DIR"/.bin ~

# Terminal
mkdir -p ~/.config/kitty
ln -sf "$DIR"/.dircolors ~
ln -sf "$DIR"/.config/kitty/kitty.conf ~/.config/kitty
ln -sf "$DIR"/.config/kitty/default-kitty ~/.config/kitty

# Tmux
ln -sf "$DIR"/.tmux.conf ~

# Git
cp -f "$DIR"/.gitconfig ~
ln -sf "$DIR"/.gitk ~

# Input devices
ln -sf "$DIR"/.input_config.sh ~
sudo ln -sf "$DIR"/.peripherals/40-libinput.conf /usr/share/X11/xorg.conf.d
sudo ln -sf "$DIR"/.peripherals/51-synaptics-quirks.conf /usr/share/X11/xorg.conf.d
sudo ln -sf "$DIR"/.peripherals/70-synaptics.conf /usr/share/X11/xorg.conf.d

# Python
mkdir -p ~/.ipython/profile_default/startup
cp -r "$DIR"/.jupyter ~
ln -sf "$DIR"/.config/flake8 ~/.config
ln -sf "$DIR"/.ipython/profile_default/startup/fzf_history.py \
   ~/.ipython/profile_default/startup

# Julia
mkdir -p ~/.julia/config
ln -sf "$DIR"/.config/startup.jl ~/.julia/config

# ..:: Install modules ::..

source .modules/functions.sh
source .modules/dev_tools.sh
source .modules/cpp.sh
source .modules/python.sh
source .modules/julia.sh
source .modules/csharp.sh
source .modules/javascript.sh
source .modules/usability.sh
source .modules/productivity.sh
source .modules/vscode.sh
source .modules/emacs.sh
source .modules/hardware.sh

# ..:: Finishing tasks ::..

update_bashrc

# Remove stale modules
sudo apt-get -yf autoremove
