#!/bin/bash
#
# Installation script for the dotfiles, and to configure the Linux environment.
#
# Run using:
# $ ./install
#
# Author: Danylo Malyuta, 2020.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if [ "$(pwd)" != "$DIR" ]; then
   >&2 echo "ERROR: please run ./install from the root of the dotfiles repo."
   exit 1
fi

# ..:: Copy dotfiles to home directory ::..

# Bash
ln -sf "$DIR"/.profile ~
ln -sf "$DIR"/.bash_aliases ~
ln -sf "$DIR"/.local.bashrc ~

# Various executable scripts
if [ ! -f ./.bin/colorizer/Library/colorizer.sh ]; then
   git submodule update --init --recursive
fi
ln -sf "$DIR"/.bin ~

# Terminal
mkdir -p ~/.config/kitty
ln -sf "$DIR"/.dircolors ~
ln -sf "$DIR"/.config/kitty/kitty.conf ~/.config/kitty
ln -sf "$DIR"/.config/kitty/default-kitty ~/.config/kitty

# Tmux
ln -sf "$DIR"/.tmux.conf ~

# Git
cp -f "$DIR"/.gitconfig ~
ln -sf "$DIR"/.gitk ~

# Python
mkdir -p ~/.ipython/profile_default/startup
cp -r "$DIR"/.jupyter ~
ln -sf "$DIR"/.config/flake8 ~/.config
ln -sf "$DIR"/.ipython/profile_default/startup/fzf_history.py \
   ~/.ipython/profile_default/startup

# Julia
mkdir -p ~/.julia/config
ln -sf "$DIR"/.config/startup.jl ~/.julia/config

# ..:: Install modules ::..

source .modules/functions.sh
source .modules/dev_tools.sh
source .modules/cpp.sh
source .modules/python.sh
source .modules/julia.sh
source .modules/csharp.sh
source .modules/javascript.sh
source .modules/usability.sh
source .modules/productivity.sh
source .modules/vscode.sh
source .modules/emacs.sh
source .modules/hardware.sh

# ..:: Finishing tasks ::..

update_bashrc

# Remove stale modules
sudo apt-get -yf autoremove
