#!/bin/bash
#
# Syncing script for the local directory with the remote repository.
#
# To get content from remote:
# $ ./sync pull
#
# To upload content to remote:
# $ ./sync push
#
# To do both at once:
# $ ./sync bidi
#
# Author: Danylo Malyuta, 2022.

OPERATION_KIND=$1
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source .modules/sync/vscode.sh

push_operation() {
    # Run pre-push commands
    vscode_cleanup_settings

    # Push to remote
    git add --all
    git --no-pager status
    read -p 'Commit message: ' COMMIT_MESSAGE
    git commit -m "$COMMIT_MESSAGE"
    git push

    # Post-push actions
    vscode_restore_settings
}

pull_operation() {
    git pull
}

if [[ $OPERATION_KIND = pull ]]; then
    pull_operation
elif [[ $OPERATION_KIND = push ]]; then
    push_operation
elif [[ $OPERATION_KIND = bidi ]]; then
    pull_operation
    push_operation
else
    cat << EOF
Unknown command.
To download from remote:
  $ sync pull
To upload to remote:
  $ sync push
To do pull and then push:
  $ sync bidi
EOF
fi
